### ISSUE TITLE
Not working on neovim

### ISSUE THREAD

**Issue by lucasprag** [rbtnn/vim-mario#1]
Hi, this plugin is an awesome idea =)

I would love to play it on nvim.

I use a vim fork called neovim.io, but it is not working on it. I see the Mario falling quickly and then:
![mario](https://cloud.githubusercontent.com/assets/2293178/26457137/7c4152c6-4145-11e7-853a-f8e556838af9.png)

NVIM 0.1.7
Ubuntu 16

Thanks

**Comment by rbtnn** [comment]
@Lucasosf I'm sorry. I don't want to support this for NeoVim, but welcome the PR .

**Comment by logankopas** [comment]
It actually does appear to run on neovim, you just have to make sure you set `nowrap` and make sure the font size is small
![image](https://user-images.githubusercontent.com/5623932/97619349-bdf3aa80-19e5-11eb-8e61-3a36f42b6b12.png)
